version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    ports:
      - 27017:27017

  api: 
    image: registros-backend
    ports:
      - 3001:3001
    command: npm run start
    env_file:
      - .env
    depends_on:
      - mongodb